-- DM practice content generated from dm-practice-24-v3.json.
-- Fail-fast inserts: any ID/ref collision aborts the transaction.
-- Content-version triggers update versions automatically; do not bump them manually.
BEGIN;
DO $migration$
DECLARE
  v_base_order integer;
BEGIN
  SELECT COALESCE(MAX(order_index), 0) INTO v_base_order FROM decision_making_questions;
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'Amber Permit Rules', 'syllogism'::dm_question_type, 'At a fictional permit office, every amber permit is inspected. No inspected permit is approved automatically. Some amber permits are renewals. Every renewal permit carries a barcode. Decide whether each statement follows from these rules.', NULL, NULL, NULL, NULL, NULL, v_base_order + 1, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'Some renewal permits are inspected.', 'Yes', 'Some renewals are amber, and every amber permit is inspected.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'No amber permit is approved automatically.', 'Yes', 'Every amber permit is inspected, and no inspected permit is approved automatically.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'Every barcoded permit is amber.', 'No', 'The rules say renewals carry barcodes, but do not restrict barcodes to amber permits.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'Some barcoded permits are not approved automatically.', 'Yes', 'The amber renewals exist; each has a barcode and, as an inspected amber permit, is not approved automatically.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('f1d045ff-a3b1-4bd7-9901-d6ed31b84270'::uuid, 'Some inspected permits are amber.', 'Yes', 'The stated amber renewals exist, so at least those amber permits are inspected.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'Tile Workshop Rules', 'syllogism'::dm_question_type, 'In a fictional tile workshop, every glazed tile is kiln-fired. Some kiln-fired tiles are hand-painted. No hand-painted tile is sold loose. Every tile sold loose has a label. Decide whether each statement follows.', NULL, NULL, NULL, NULL, NULL, v_base_order + 2, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'Some kiln-fired tiles are not sold loose.', 'Yes', 'The hand-painted kiln-fired tiles exist and no hand-painted tile is sold loose.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'Every glazed tile is hand-painted.', 'No', 'Glazed tiles are kiln-fired, but kiln firing does not imply hand painting.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'No hand-painted tile is sold loose.', 'Yes', 'This is an explicit rule.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'Some labelled tiles are glazed.', 'No', 'Neither the existence of loose tiles nor a link from loose to glazed is given.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('cac6abc2-93cb-4129-a31d-290ec0279fee'::uuid, 'Some kiln-fired tiles are hand-painted.', 'Yes', 'This is explicitly stated.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'Restricted Archive Files', 'syllogism'::dm_question_type, 'In a fictional archive, every encrypted file is backed up. A file can be backed up only if it is indexed. Some encrypted files are restricted. No restricted file is shared publicly. Decide whether each statement follows.', NULL, NULL, NULL, NULL, NULL, v_base_order + 3, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'Some restricted files are indexed.', 'Yes', 'The encrypted restricted files exist. Encrypted files are backed up, and backed-up files must be indexed.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'Every encrypted file is indexed.', 'Yes', 'Encryption implies backup; backup requires indexing.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'No encrypted file is shared publicly.', 'No', 'Only the restricted encrypted files are known to be unshared; other encrypted files could be shared.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'Some backed-up files are restricted.', 'Yes', 'The encrypted restricted files exist and are all backed up.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('7b16280a-94d9-4e5d-9029-9bb35f023170'::uuid, 'Every indexed file is backed up.', 'No', 'Backup requires indexing; the converse is not stated.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('b72ef91a-3680-4f37-aa0f-89998470d7b2'::uuid, 'Display Crate Sequence', 'logic_puzzle'::dm_question_type, 'Five display crates A, B, C, D and E are placed in a row from left to right. A is third. C is immediately to the right of A. B is somewhere to the left of D, and D is somewhere to the left of A. Which crate is first?', NULL, NULL, NULL, 'B', 'A is third and C fourth. B and D must occupy the first two places in that order; E is fifth. B is first.', v_base_order + 4, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b72ef91a-3680-4f37-aa0f-89998470d7b2'::uuid, 'A', 'A', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b72ef91a-3680-4f37-aa0f-89998470d7b2'::uuid, 'B', 'B', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b72ef91a-3680-4f37-aa0f-89998470d7b2'::uuid, 'C', 'D', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b72ef91a-3680-4f37-aa0f-89998470d7b2'::uuid, 'D', 'E', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('2fea6610-f787-41a0-93be-28344a314aeb'::uuid, 'Workshop Station Assignments', 'logic_puzzle'::dm_question_type, 'Four makers, Imani, Joel, Kira and Luca, each use a different station: printing, cutting, painting or packing. Imani does not print or paint. Joel uses the station immediately before packing in the fixed order printing, cutting, painting, packing. Kira does not cut. Luca prints. Which station does Imani use?', NULL, NULL, NULL, 'B', 'Joel paints because painting immediately precedes packing. Luca prints. The remaining stations are cutting and packing; Kira cannot cut, so Kira packs and Imani cuts.', v_base_order + 5, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('2fea6610-f787-41a0-93be-28344a314aeb'::uuid, 'A', 'Printing', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('2fea6610-f787-41a0-93be-28344a314aeb'::uuid, 'B', 'Cutting', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('2fea6610-f787-41a0-93be-28344a314aeb'::uuid, 'C', 'Painting', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('2fea6610-f787-41a0-93be-28344a314aeb'::uuid, 'D', 'Packing', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('d822dd15-d4f7-4911-8187-2b9c6c356d91'::uuid, 'Harbour Launch Slots', 'logic_puzzle'::dm_question_type, 'Five launches named Alder, Birch, Cedar, Dune and Elm leave at 09:00, 09:15, 09:30, 09:45 and 10:00, one per slot. Birch leaves immediately after Alder. Dune leaves after Birch but before Elm. Cedar leaves after Alder but not immediately after Birch. Elm leaves at 10:00. Which launch leaves at 09:30?', NULL, NULL, NULL, 'D', 'Elm is fifth. Dune must be before Elm and after consecutive Alder-Birch. If Alder-Birch occupied slots 1-2, Cedar must follow Alder but cannot be slot 3, so Cedar=4 and Dune=3. If they occupied slots 2-3, Cedar would need slot 4, leaving no slot for Dune before Elm. Therefore Dune is at 09:30.', v_base_order + 6, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('d822dd15-d4f7-4911-8187-2b9c6c356d91'::uuid, 'A', 'Alder', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('d822dd15-d4f7-4911-8187-2b9c6c356d91'::uuid, 'B', 'Birch', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('d822dd15-d4f7-4911-8187-2b9c6c356d91'::uuid, 'C', 'Cedar', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('d822dd15-d4f7-4911-8187-2b9c6c356d91'::uuid, 'D', 'Dune', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'Repair Desk Outcomes', 'interpreting_info'::dm_question_type, 'A fictional repair desk recorded items brought in and successfully repaired over two Saturdays. Each item belongs to exactly one category. Decide whether each statement follows from the table.', '{"headers":["Category","First: brought","First: repaired","Second: brought","Second: repaired"],"rows":[["Lamps","18","12","22","17"],["Radios","15","9","19","14"],["Toys","20","15","18","13"]]}'::jsonb, NULL, NULL, NULL, NULL, v_base_order + 7, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'More lamps than radios were brought in across both Saturdays.', 'Yes', 'Lamps: 18+22=40; radios: 15+19=34.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'The total number of successful repairs was higher on the second Saturday.', 'Yes', 'First Saturday: 12+9+15=36. Second: 17+14+13=44.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'Every category had more successful repairs on the second Saturday.', 'No', 'The toy category fell from 15 to 13 successful repairs.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'The repair rate for radios was exactly 60% on the first Saturday.', 'Yes', 'Nine of fifteen radios were repaired: 9/15=60%.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8b01c2cb-8622-4e6a-9b00-42f3a71f7f74'::uuid, 'More toys will be repaired on the third Saturday than on the second.', 'No', 'The table provides no third-Saturday result or valid prediction.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'Shuttle Passenger Record', 'interpreting_info'::dm_question_type, 'A fictional shuttle carried 96 distinct passengers on Monday. Of these, 42 boarded before noon and the remainder boarded later. Thirty passengers travelled with a bicycle; 18 of those boarded before noon. Every passenger boarded exactly once. Decide whether each statement follows.', NULL, NULL, NULL, NULL, NULL, v_base_order + 8, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'Fifty-four passengers boarded after noon.', 'Yes', '96-42=54.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'Twelve passengers with a bicycle boarded after noon.', 'Yes', 'Thirty travelled with a bicycle and 18 boarded before noon, leaving 12 after noon.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'More than half of the before-noon passengers travelled with a bicycle.', 'No', 'Only 18 of 42 did; half of 42 is 21.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'More passengers without a bicycle boarded after noon than before noon.', 'Yes', 'After noon without bicycle: 54-12=42; before noon without bicycle: 42-18=24.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('8383651a-ae22-4096-b8b3-d29328677eff'::uuid, 'At least one passenger who boarded later will bring a bicycle on Tuesday.', 'No', 'Monday data gives no Tuesday behaviour.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'Helpline Transfer Audit', 'interpreting_info'::dm_question_type, 'A fictional helpline reports calls answered at three desks during one shift. Each call is answered by exactly one desk; transferred calls are included in that desk’s answered total and are transferred once. Decide whether each statement follows.', '{"headers":["Desk","Calls answered","Calls transferred"],"rows":[["North","80","20"],["South","120","36"],["East","100","15"]]}'::jsonb, NULL, NULL, NULL, NULL, v_base_order + 9, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'The South desk transferred the largest number of calls.', 'Yes', 'South transferred 36, compared with North 20 and East 15.', 1);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'The North desk transferred one quarter of its answered calls.', 'Yes', '20/80=1/4.', 2);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'The combined transfer rate across all desks was less than one quarter.', 'Yes', 'There were 20+36+15=71 transfers out of 80+120+100=300 calls; 71/300 is about 23.67%.', 3);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'East had a lower transfer rate than South.', 'Yes', 'East: 15/100=15%; South: 36/120=30%.', 4);
  INSERT INTO decision_making_question_statements (question_id, statement_text, correct_answer, answer_reason, order_index) VALUES ('d9aae1fd-d6e2-4408-81ee-7a2c661c6acb'::uuid, 'The South desk answered more calls without transfer than the other two desks combined.', 'No', 'South had 120-36=84; North and East together had (80-20)+(100-15)=145.', 5);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('b0f99a28-6127-40ab-b548-bce5ef933dc2'::uuid, 'Repair Booking Trial', 'recognising_assumptions'::dm_question_type, 'A fictional repair workshop wants to introduce optional online appointment booking to reduce the average waiting time for visitors. Which is the strongest argument?', NULL, NULL, NULL, 'C', 'The six-week comparison directly measures the proposed outcome under comparable staffing and hours. The other arguments concern preference or minor administration rather than average waiting time.', v_base_order + 10, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b0f99a28-6127-40ab-b548-bce5ef933dc2'::uuid, 'A', 'Yes; visitors often prefer to know their appointment time in advance.', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b0f99a28-6127-40ab-b548-bce5ef933dc2'::uuid, 'B', 'No; the workshop’s wall clock would need to be checked more often.', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b0f99a28-6127-40ab-b548-bce5ef933dc2'::uuid, 'C', 'Yes; in a six-week trial with the same staffing and opening hours, mean waiting time fell from 28 to 16 minutes when appointment slots were offered.', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('b0f99a28-6127-40ab-b548-bce5ef933dc2'::uuid, 'D', 'No; some visitors would still prefer to arrive without booking.', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('c2e726ed-8cb5-4d7e-88ba-9a6f1118b8ac'::uuid, 'Early River Shuttle', 'recognising_assumptions'::dm_question_type, 'A fictional town considers adding a 07:00 river shuttle to reduce crowding on its existing 07:30 departure. Which is the strongest argument?', NULL, NULL, NULL, 'C', 'The trial directly shows that the proposed trip did not reduce crowding on the 07:30 service. The other arguments do not measure that outcome.', v_base_order + 11, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('c2e726ed-8cb5-4d7e-88ba-9a6f1118b8ac'::uuid, 'A', 'Yes; many residents say an earlier departure would feel convenient.', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('c2e726ed-8cb5-4d7e-88ba-9a6f1118b8ac'::uuid, 'B', 'Yes; the extra vessel has attractive new seats.', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('c2e726ed-8cb5-4d7e-88ba-9a6f1118b8ac'::uuid, 'C', 'No; a trial of the 07:00 trip drew mostly passengers who had previously travelled after 08:00, while the number aboard the 07:30 trip was unchanged.', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('c2e726ed-8cb5-4d7e-88ba-9a6f1118b8ac'::uuid, 'D', 'No; some passengers dislike travelling before sunrise.', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('fbaf9861-744c-45f3-9879-5fad8c0e62eb'::uuid, 'Archive Catalogue Copies', 'recognising_assumptions'::dm_question_type, 'A fictional archive keeps its only catalogue on paper in one building. Should it scan the catalogue and store duplicate digital copies in two other buildings to reduce the risk of losing all catalogue records if the archive building is damaged? Which is the strongest argument?', NULL, NULL, NULL, 'A', 'Copies in other buildings would remain available if damage destroyed the only paper catalogue, directly reducing the stated risk of total record loss. Convenience, staff preference and a temporary need for electricity do not address permanent loss as directly.', v_base_order + 12, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('fbaf9861-744c-45f3-9879-5fad8c0e62eb'::uuid, 'A', 'Yes; if damage destroys the paper catalogue in the archive building, the copies held elsewhere would preserve its records.', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('fbaf9861-744c-45f3-9879-5fad8c0e62eb'::uuid, 'B', 'Yes; visitors often enjoy using searchable screens.', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('fbaf9861-744c-45f3-9879-5fad8c0e62eb'::uuid, 'C', 'No; some staff prefer reading the original handwritten pages.', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('fbaf9861-744c-45f3-9879-5fad8c0e62eb'::uuid, 'D', 'No; the buildings holding the copies would need electricity to open the files.', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('80fd9429-e35b-42df-8c4a-2e29db932c4e'::uuid, 'Coastal Trail Signs', 'venn_diagram'::dm_question_type, 'A diagram shows 58 signs on a fictional coastal trail. Set A means “mentions birds” and set B means “mentions tides”. Numbers give the number of signs in each exclusive region.

How many signs mention birds but not tides?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Birds","shape":"circle"},{"id":"set2","label":"Tides","shape":"circle"}],"regions":{"set1_only":18,"set2_only":13,"set1_set2":11,"outside":16}}'::jsonb, NULL, 'C', 'The birds-only region is 18. The overlap of 11 mentions both, so it is excluded.', v_base_order + 13, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('80fd9429-e35b-42df-8c4a-2e29db932c4e'::uuid, 'A', '11', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('80fd9429-e35b-42df-8c4a-2e29db932c4e'::uuid, 'B', '13', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('80fd9429-e35b-42df-8c4a-2e29db932c4e'::uuid, 'C', '18', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('80fd9429-e35b-42df-8c4a-2e29db932c4e'::uuid, 'D', '29', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('a10ba3a4-0fa6-488c-ade8-dbf012618322'::uuid, 'Studio Workshop Enrolment', 'venn_diagram'::dm_question_type, 'The diagram classifies 64 fictional studio members by enrolment in clay, print and textile workshops. Each number is the count in that exclusive region.

How many members take print, whether or not they take another workshop?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Clay","shape":"circle"},{"id":"set2","label":"Print","shape":"circle"},{"id":"set3","label":"Textile","shape":"circle"}],"regions":{"set1_only":10,"set2_only":9,"set3_only":8,"set1_set2":7,"set1_set3":6,"set2_set3":5,"set1_set2_set3":4,"outside":15}}'::jsonb, NULL, 'C', 'Print includes print only 9, clay-and-print only 7, print-and-textile only 5, and all three 4: 9+7+5+4=25.', v_base_order + 14, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('a10ba3a4-0fa6-488c-ade8-dbf012618322'::uuid, 'A', '16', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('a10ba3a4-0fa6-488c-ade8-dbf012618322'::uuid, 'B', '21', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('a10ba3a4-0fa6-488c-ade8-dbf012618322'::uuid, 'C', '25', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('a10ba3a4-0fa6-488c-ade8-dbf012618322'::uuid, 'D', '29', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('61a5a8b4-20d2-4b57-b504-6c542a26a872'::uuid, 'Community Event Roles', 'venn_diagram'::dm_question_type, 'The diagram shows 72 people at a fictional event, classified by whether they helped with setup, registration and clean-up. Region numbers are exclusive.

How many helped with exactly two of the three tasks?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Setup","shape":"circle"},{"id":"set2","label":"Registration","shape":"circle"},{"id":"set3","label":"Clean-up","shape":"circle"}],"regions":{"set1_only":12,"set2_only":10,"set3_only":9,"set1_set2":6,"set1_set3":8,"set2_set3":5,"set1_set2_set3":4,"outside":18}}'::jsonb, NULL, 'B', 'The exactly-two regions contain 6, 8 and 5 people. Their sum is 19; the all-three region is excluded.', v_base_order + 15, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('61a5a8b4-20d2-4b57-b504-6c542a26a872'::uuid, 'A', '15', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('61a5a8b4-20d2-4b57-b504-6c542a26a872'::uuid, 'B', '19', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('61a5a8b4-20d2-4b57-b504-6c542a26a872'::uuid, 'C', '23', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('61a5a8b4-20d2-4b57-b504-6c542a26a872'::uuid, 'D', '27', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('7c2c3af5-ffdf-4c56-9eb1-d24c1490c99d'::uuid, 'Park Volunteer Skills', 'venn_diagram'::dm_question_type, 'The diagram classifies 80 volunteers at a fictional park by map reading, first aid and equipment maintenance. Each region count is exclusive, and every volunteer has an equal chance of being selected.

Among volunteers who have first-aid skills, what proportion also have map-reading skills?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Map reading","shape":"circle"},{"id":"set2","label":"First aid","shape":"circle"},{"id":"set3","label":"Maintenance","shape":"circle"}],"regions":{"set1_only":13,"set2_only":12,"set3_only":11,"set1_set2":8,"set1_set3":7,"set2_set3":6,"set1_set2_set3":5,"outside":18}}'::jsonb, NULL, 'A', 'First-aid volunteers: 12+8+6+5=31. Those also with map reading: 8+5=13. The conditional proportion is 13/31.', v_base_order + 16, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7c2c3af5-ffdf-4c56-9eb1-d24c1490c99d'::uuid, 'A', '13/31', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7c2c3af5-ffdf-4c56-9eb1-d24c1490c99d'::uuid, 'B', '13/26', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7c2c3af5-ffdf-4c56-9eb1-d24c1490c99d'::uuid, 'C', '5/31', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7c2c3af5-ffdf-4c56-9eb1-d24c1490c99d'::uuid, 'D', '8/31', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('45d47239-046a-4ade-98a3-fa3de9802138'::uuid, 'Observatory Alert Channels', 'probabilistic'::dm_question_type, 'At a fictional observatory, two independent alert channels operate on a given night. Channel A sends an alert with probability 0.30; channel B sends an alert with probability 0.20. What is the probability that exactly one channel sends an alert?', NULL, NULL, NULL, 'B', 'Exactly one means A alone or B alone: (0.30×0.80)+(0.70×0.20)=0.24+0.14=0.38.', v_base_order + 17, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('45d47239-046a-4ade-98a3-fa3de9802138'::uuid, 'A', '0.06', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('45d47239-046a-4ade-98a3-fa3de9802138'::uuid, 'B', '0.38', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('45d47239-046a-4ade-98a3-fa3de9802138'::uuid, 'C', '0.44', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('45d47239-046a-4ade-98a3-fa3de9802138'::uuid, 'D', '0.50', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('8efec042-4316-4d7d-a909-7de9beb2433b'::uuid, 'Rehearsal Room Collision', 'probabilistic'::dm_question_type, 'Three performers independently choose one of four rehearsal rooms. Each performer is equally likely to choose any room. What is the probability that at least two performers choose the same room?', NULL, NULL, NULL, 'D', 'Use the complement. For all three performers to choose different rooms, the first can choose any room, the second must choose one of the other three, and the third one of the remaining two: (4/4)×(3/4)×(2/4)=3/8. Therefore the probability that at least two choose the same room is 1−3/8=5/8.', v_base_order + 18, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('8efec042-4316-4d7d-a909-7de9beb2433b'::uuid, 'A', '1/4', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('8efec042-4316-4d7d-a909-7de9beb2433b'::uuid, 'B', '3/8', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('8efec042-4316-4d7d-a909-7de9beb2433b'::uuid, 'C', '1/2', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('8efec042-4316-4d7d-a909-7de9beb2433b'::uuid, 'D', '5/8', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('f5541786-42ff-4db3-9e49-fdf982e875e3'::uuid, 'Ferry Rain Covers', 'probabilistic'::dm_question_type, 'A fictional ferry carried 120 passengers on its morning trip and 80 on its evening trip. On the morning trip, 30 passengers took a rain cover; on the evening trip, 40 did. One of the 200 passengers is chosen uniformly at random. Given that the selected passenger took a rain cover, what is the probability that they travelled in the evening?', NULL, NULL, NULL, 'C', 'Among rain-cover users there were 30+40=70 passengers, of whom 40 travelled in the evening. Conditional probability = 40/70=4/7.', v_base_order + 19, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('f5541786-42ff-4db3-9e49-fdf982e875e3'::uuid, 'A', '1/5', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('f5541786-42ff-4db3-9e49-fdf982e875e3'::uuid, 'B', '2/5', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('f5541786-42ff-4db3-9e49-fdf982e875e3'::uuid, 'C', '4/7', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('f5541786-42ff-4db3-9e49-fdf982e875e3'::uuid, 'D', '1/2', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('4c84d495-18b8-4ef5-a86f-1beb34142de1'::uuid, 'Display Volume Order', 'probabilistic'::dm_question_type, 'Six distinct display volumes are arranged in a random order on one shelf. Two named volumes, Atlas and Beacon, are among the six. What is the probability that Atlas and Beacon are next to each other?', NULL, NULL, NULL, 'B', 'Treat Atlas and Beacon as one block. The block and four other volumes have 5! orders, and the two named volumes have 2 internal orders. Thus favourable orders = 2×5!, out of 6! total: 2/6=1/3.', v_base_order + 20, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('4c84d495-18b8-4ef5-a86f-1beb34142de1'::uuid, 'A', '1/6', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('4c84d495-18b8-4ef5-a86f-1beb34142de1'::uuid, 'B', '1/3', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('4c84d495-18b8-4ef5-a86f-1beb34142de1'::uuid, 'C', '2/5', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('4c84d495-18b8-4ef5-a86f-1beb34142de1'::uuid, 'D', '1/2', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('3aa6e000-327c-45d7-b2f5-26142b4b7177'::uuid, 'Community Radio Programme Tags', 'venn_diagram'::dm_question_type, 'A station has 39 programmes. A programme may carry the Music, Talk, or Local tag. Of these, 12 have Music, 18 have Talk, and 11 have Local. Four have both Music and Talk; three have both Talk and Local; none have both Music and Local. Five programmes have none of the three tags. Which diagram represents these data? Each number is the count in that exclusive region.', NULL, NULL, NULL, 'A', 'Because Music and Local never overlap, no programme can have all three tags. Music-only is 12−4=8; Talk-only is 18−4−3=11; Local-only is 11−3=8. With five outside, diagram A matches every count and overlap.', v_base_order + 21, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('3aa6e000-327c-45d7-b2f5-26142b4b7177'::uuid, 'A', '', '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Music","shape":"square"},{"id":"set2","label":"Talk","shape":"oval"},{"id":"set3","label":"Local","shape":"diamond"}],"regions":{"set1_only":8,"set2_only":11,"set3_only":8,"set1_set2":4,"set2_set3":3,"outside":5}}'::jsonb, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('3aa6e000-327c-45d7-b2f5-26142b4b7177'::uuid, 'B', '', '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Music","shape":"square"},{"id":"set2","label":"Talk","shape":"oval"},{"id":"set3","label":"Local","shape":"diamond"}],"regions":{"set1_only":12,"set2_only":18,"set3_only":4,"outside":5}}'::jsonb, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('3aa6e000-327c-45d7-b2f5-26142b4b7177'::uuid, 'C', '', '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Music","shape":"square"},{"id":"set2","label":"Talk","shape":"oval"},{"id":"set3","label":"Local","shape":"diamond"}],"regions":{"set1_only":20,"set1_set2":8,"set1_set3":"0","set1_set2_set3":6,"outside":5}}'::jsonb, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('3aa6e000-327c-45d7-b2f5-26142b4b7177'::uuid, 'D', '', '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Music","shape":"square"},{"id":"set2","label":"Talk","shape":"oval"},{"id":"set3","label":"Local","shape":"diamond"}],"regions":{"set1_only":8,"set2_only":14,"set3_only":8,"set1_set2":4,"outside":5}}'::jsonb, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('5297e7b2-a46d-4750-9a7a-09db32602f59'::uuid, 'Observatory Image Archive', 'venn_diagram'::dm_question_type, 'Every digitised observatory image has been checked, and every published image has been checked. Some checked images are both digitised and published. The diagram uses a rectangle for Checked, a circle for Digitised, and a diamond for Published. Each letter identifies one exclusive region. An image in region Q is compared with an image in region R. Which statement must be true of both images?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Checked","shape":"rectangle"},{"id":"set2","label":"Digitised","shape":"circle"},{"id":"set3","label":"Published","shape":"diamond"}],"regions":{"set1_only":"P","set1_set2":"Q","set1_set3":"T","set1_set2_set3":"R","outside":"S"}}'::jsonb, NULL, 'B', 'Q lies in Checked and Digitised but outside Published. R lies in all three. Both images have therefore been digitised. Only the R image is published, and both have been checked.', v_base_order + 22, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('5297e7b2-a46d-4750-9a7a-09db32602f59'::uuid, 'A', 'Both were published.', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('5297e7b2-a46d-4750-9a7a-09db32602f59'::uuid, 'B', 'Both were digitised.', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('5297e7b2-a46d-4750-9a7a-09db32602f59'::uuid, 'C', 'Neither was checked.', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('5297e7b2-a46d-4750-9a7a-09db32602f59'::uuid, 'D', 'Exactly one was digitised.', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('308bcd28-85d0-4149-a2fd-3f6dd456dfd3'::uuid, 'Repair Fair Route Cards', 'venn_diagram'::dm_question_type, 'At a repair fair, each of 58 visitors completes one route card indicating whether they joined Repair, Reuse, Donate, or Recycle. The diagram shows four different shapes. Each number gives a count in an exclusive region. How many visitors joined at least one of Repair or Donate?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Repair","shape":"horizontal_strip"},{"id":"set2","label":"Reuse","shape":"vertical_strip"},{"id":"set3","label":"Donate","shape":"oval"},{"id":"set4","label":"Recycle","shape":"vertical_oval"}],"regions":{"set1_only":7,"set2_only":9,"set3_only":8,"set4_only":6,"set1_set2":4,"set2_set3":5,"set3_set4":3,"set1_set4":6,"outside":10}}'::jsonb, NULL, 'D', 'Repair and Donate do not overlap, so add every region in either shape: Repair has 7+4+6=17; Donate has 8+5+3=16. The total is 33. The other 25 cards are in Reuse only, Recycle only, or outside.', v_base_order + 23, 'normal', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('308bcd28-85d0-4149-a2fd-3f6dd456dfd3'::uuid, 'A', '24', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('308bcd28-85d0-4149-a2fd-3f6dd456dfd3'::uuid, 'B', '29', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('308bcd28-85d0-4149-a2fd-3f6dd456dfd3'::uuid, 'C', '31', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('308bcd28-85d0-4149-a2fd-3f6dd456dfd3'::uuid, 'D', '33', NULL, NULL, 4);
  INSERT INTO decision_making_questions (id, title, type, stem, table_data, stimulus_diagram, venn_geometry, correct_answer, answer_reason, order_index, difficulty, hide_labels, is_free) VALUES ('7e0c5ab8-a660-4780-a9f1-617433e4056a'::uuid, 'Packaging Lab Fault Codes', 'venn_diagram'::dm_question_type, 'A packaging lab classifies samples by whether they need a retest and whether they have a seal, print, or weight fault. A sample can have at most one of the three named fault types. The diagram gives exclusive-region counts, except that the retest-only region is marked ?. The lab found that the number needing a retest is twice the number not needing one. How many samples are in the ? region?', NULL, '{"diagramLayout":"auto","sets":[{"id":"set1","label":"Retest","shape":"circle"},{"id":"set2","label":"Seal fault","shape":"diamond"},{"id":"set3","label":"Print fault","shape":"vertical_oval"},{"id":"set4","label":"Weight fault","shape":"vertical_oval"}],"regions":{"set1_only":"?","set2_only":5,"set3_only":7,"set4_only":6,"set1_set2":4,"set1_set3":6,"set1_set4":8,"outside":3}}'::jsonb, NULL, 'C', 'Outside Retest there are 5+7+6+3=21 samples. Twice as many need a retest, so Retest contains 42. The three Retest-and-fault regions contain 4+6+8=18, leaving 42−18=24 in the retest-only region.', v_base_order + 24, 'hard', FALSE, TRUE);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7e0c5ab8-a660-4780-a9f1-617433e4056a'::uuid, 'A', '18', NULL, NULL, 1);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7e0c5ab8-a660-4780-a9f1-617433e4056a'::uuid, 'B', '21', NULL, NULL, 2);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7e0c5ab8-a660-4780-a9f1-617433e4056a'::uuid, 'C', '24', NULL, NULL, 3);
  INSERT INTO decision_making_question_options (question_id, label, option_text, option_data, venn_geometry, order_index) VALUES ('7e0c5ab8-a660-4780-a9f1-617433e4056a'::uuid, 'D', '27', NULL, NULL, 4);
END
$migration$;
COMMIT;
