-- Generated VR practice content. Review before running supabase db push.
-- Source: vr-practice-20-v3.json
-- This file only inserts content; it does not alter the schema.

-- Passage 1: Harvesting Cork Without Felling the Oak
INSERT INTO verbal_reasoning_passages (id, title, body, is_free) VALUES
  ('6790da18-9bee-49c2-a98b-b044d434ecf0', 'Harvesting Cork Without Felling the Oak', 'The cork used in bottle stoppers comes from the outer bark of the cork oak, not from its wood. In Portuguese cork woodlands, specialist workers remove the bark in large sheets while leaving the tree standing. They make cuts with an axe and ease the sheets away, taking care not to injure the living layer beneath. The trunk is then marked with the final digit of the harvest year. This mark helps workers identify when a tree was last stripped; the removed bark grows back.

Harvesting has two clocks. The first concerns the tree''s size: in Portugal, the trunk must reach a circumference of at least 70 centimetres, measured 1.3 metres above the ground, before its first stripping. This usually takes about 25 years. The second clock is the interval between harvests. Portuguese rules forbid stripping a tree again in less than nine years, even if its bark appears ready sooner. The first crop, called virgin cork, is irregular and hard. It can serve uses such as flooring or insulation, but is unsuitable for quality bottle stoppers.

The second crop, taken at least nine years later, is more regular yet still generally unsuitable for those stoppers. It is from the third and later crops that cork with the desired structure is usually obtained. Thus a young tree that has just reached the minimum size does not immediately become a source of stopper-grade material. Nor does a thick-looking trunk alone tell a worker when it may next be harvested. Both the stage in the tree''s harvesting history and the time since its previous stripping matter. The system depends on skilled cutting as much as on patience: careless removal could damage the living tree on which future crops depend.', false)
;

INSERT INTO verbal_reasoning_questions
  (id, passage_id, question_text, options, correct_answer, answer_reason, order_index, difficulty)
VALUES
  ('8ea61a64-1222-4b0c-86c0-729fef8c8bda', '6790da18-9bee-49c2-a98b-b044d434ecf0', 'Why is the trunk marked after stripping?', ARRAY['To show how much cork was removed', 'To record when bark was last harvested', 'To identify the tree species for buyers', 'To indicate that the bark cannot regrow'], 'To record when bark was last harvested', 'The mark gives the final digit of the harvest year. It records timing, not yield, species or an inability to regrow.', 0, 'normal'),
  ('99e12c56-a867-4f52-8384-a7b3fb96936e', '6790da18-9bee-49c2-a98b-b044d434ecf0', 'Which cork crop is described as the first usually suitable for quality bottle stoppers?', ARRAY['The crop from a newly planted tree', 'The first crop', 'The second crop', 'The third crop'], 'The third crop', 'The passage says the first is irregular and the second still unsuitable; cork with the desired structure usually comes from the third and later crops.', 1, 'normal'),
  ('1bcb8c64-fe4e-4606-86d4-a49cbd195713', '6790da18-9bee-49c2-a98b-b044d434ecf0', 'A tree first stripped at age 25 is stripped again at 34. What is the earliest age at which its third crop could be taken under the stated rule?', ARRAY['43', '35', '34', '52'], '43', 'The minimum interval is nine years, so 34 plus nine is 43. Ages 34 and 35 are too soon; 52 is later than necessary.', 2, 'hard'),
  ('30e98bb6-944e-4b25-8a2a-2e4073262353', '6790da18-9bee-49c2-a98b-b044d434ecf0', 'Which claim best captures the passage’s main point?', ARRAY['Cork quality depends only on the thickness of a trunk.', 'The first harvest supplies most quality stoppers.', 'Repeated bark harvests require both careful technique and waiting.', 'Cork production requires trees to be felled after each crop.'], 'Repeated bark harvests require both careful technique and waiting.', 'The passage links skilled bark removal with minimum size, nine-year intervals and crop stage. Thickness alone is insufficient, the first crop is unsuitable, and the tree remains standing.', 3, 'normal')
;

-- Passage 2: Patterns on a Marbling Bath
INSERT INTO verbal_reasoning_passages (id, title, body, is_free) VALUES
  ('e63d2f47-245b-463c-b038-7406b1264c96', 'Patterns on a Marbling Bath', 'A marbled sheet is made by floating colour on a liquid bath and transferring the resulting pattern onto paper. In one traditional method, the liquid is thickened with a gum or with carrageenan, a material obtained from seaweed. This thickened bath supports drops of colour at its surface while the maker guides them with a comb or another tool. When paper is laid carefully onto the surface, it picks up the pattern. The artist has to work with moving liquid, so the design involves both deliberate gestures and effects that cannot be controlled completely.

The Turkish tradition known as ebru has long been associated with the decoration of books and calligraphic pages. The Metropolitan Museum of Art describes marbled borders around calligraphy in a manuscript album, where the colours frame rather than replace the writing. Patterns may include flowers, speckled areas and combed lines. A comb can turn a field of floating colour into a regular design, but an uncombed pattern can also be valued for its movement. In either case, the pattern exists on the bath before it appears on the paper.

Marbling has appeared in more than one cultural tradition. Japanese suminagashi, meaning “floating ink”, also transfers marks from water to paper, although its familiar rings of ink are produced differently from many thickened-bath patterns. European bookbinders used marbled sheets for covers and endpapers, the leaves joining a book''s pages to its cover. These shared uses do not prove that every maker followed the same recipe. Describing a sheet simply as “marbled” identifies the broad method and visual effect, but it does not by itself reveal whether a comb was used or which liquid and colours produced it.', false)
;

INSERT INTO verbal_reasoning_questions
  (id, passage_id, question_text, options, correct_answer, answer_reason, order_index, difficulty)
VALUES
  ('f7077645-6bd9-4cdc-a0e2-51e546fba34d', 'e63d2f47-245b-463c-b038-7406b1264c96', 'What happens immediately before the pattern is transferred to paper in the described thickened-bath method?', ARRAY['The completed sheet is placed inside a book.', 'The gum is removed from the liquid.', 'Colour is floated and arranged on the bath.', 'The paper is painted after drying.'], 'Colour is floated and arranged on the bath.', 'The pattern is first formed from floating colour and then picked up by paper. Binding follows later; the gum is not removed, and the pattern is not painted on after drying.', 0, 'normal'),
  ('8719b958-9359-4140-b6e4-e8a88b64b0bb', 'e63d2f47-245b-463c-b038-7406b1264c96', 'Why does the passage mention marbled borders around calligraphy?', ARRAY['To show that marbling could complement written pages', 'To show that ebru always replaced writing', 'To prove that all ebru patterns were combed', 'To date the invention of Japanese suminagashi'], 'To show that marbling could complement written pages', 'The album example shows coloured borders framing writing. It says nothing about all patterns being combed or the date of suminagashi, and the decoration does not replace text.', 1, 'normal'),
  ('32a9fdc7-9d39-4fc7-9c7f-93e637a61961', 'e63d2f47-245b-463c-b038-7406b1264c96', 'A conservator wants to distinguish a combed marbling pattern from an uncombed one. Which observation would provide the strongest evidence?', ARRAY['Concentric rings of floating ink transferred onto the paper', 'Colours suspended on a bath thickened with gum', 'Speckled colours framing a page of calligraphy', 'Regular parallel lines shaped in the floating colour'], 'Regular parallel lines shaped in the floating colour', 'The passage links combing to regular designs and specifically lists combed lines, so regular parallel lines shaped in floating colour are the strongest evidence. Concentric rings are associated with suminagashi, a different described method; a gum-thickened bath supports colour whether or not it is combed; and speckled calligraphic borders identify a motif and use, not the tool that shaped them. The lines support comb use without proving it absolutely.', 2, 'hard'),
  ('0598950c-5a2d-4661-b6f7-4d9abf634dfe', 'e63d2f47-245b-463c-b038-7406b1264c96', 'Which conclusion is supported about sheets called “marbled”?', ARRAY['They all use carrageenan rather than gum.', 'They can share a broad method without sharing a precise recipe.', 'They must be used as book covers.', 'They originate from one documented cultural tradition.'], 'They can share a broad method without sharing a precise recipe.', 'The final paragraph says the label does not identify a single recipe. Gum and carrageenan are alternatives, sheets have several uses, and multiple traditions are described.', 3, 'normal')
;

-- Passage 3: Working to the Rhythm of a Tide Mill
INSERT INTO verbal_reasoning_passages (id, title, body, is_free) VALUES
  ('2ec286c7-0754-4e7c-b994-202d18e04bc1', 'Working to the Rhythm of a Tide Mill', 'A tide mill uses a change in sea level to create a head of water: a difference in height that can drive a wheel. Its dam encloses a mill pond beside an estuary or inlet. As the incoming tide rises, water enters the pond through sluice gates. Once the tide turns, the gates retain that water while the sea outside falls. The stored water can then be released through a channel past the mill wheel, which turns machinery such as millstones. The tide has supplied the water and its height; the miller controls its release.

This arrangement differs from a river mill fed continuously by a stream. A tide mill does not simply run whenever waves reach the shore. It must first fill its pond and then wait for a useful difference between pond and sea levels. Once released, the stored water gradually loses its height advantage, so work is limited by the available head and the amount in the pond. The tide will refill the pond in a later cycle, but the timing of useful power changes with the tide rather than following a fixed daily working hour.

Historic England identifies tide mills as a distinct form of watermill, while noting that much of the wheel and mill machinery resembles that of other watermills. At Totton and Eling in Hampshire, a surviving mill stands on the seaward side of a dam across the mouth of Bartley Water. Historic England records a working waterwheel, millstones and sluice gear there. These remains make the arrangement visible: the dam and gates manage the supply, and the familiar wheel and stones perform the grinding. To understand the mill, therefore, it is necessary to consider both its ordinary milling equipment and the changing water levels outside.', false)
;

INSERT INTO verbal_reasoning_questions
  (id, passage_id, question_text, options, correct_answer, answer_reason, order_index, difficulty)
VALUES
  ('10d52d04-0f6e-49b8-9a95-df8f9d2f96b9', '2ec286c7-0754-4e7c-b994-202d18e04bc1', 'What creates the head of water used by the tide mill?', ARRAY['The millstones lifting seawater into the pond', 'A river flowing constantly over the wheel', 'Waves striking the wheel directly', 'A difference between stored pond water and the falling sea'], 'A difference between stored pond water and the falling sea', 'The passage defines the head as a height difference after the pond retains high-tide water while the sea falls. Stones do not lift water; a stream describes a river mill; waves do not drive the wheel directly.', 0, 'normal'),
  ('fc79e195-a26e-4611-bb2d-89899f95de36', '2ec286c7-0754-4e7c-b994-202d18e04bc1', 'Why must the mill wait after the pond has filled?', ARRAY['The next incoming tide must refill the pond before each use.', 'The outside sea must fall enough to give the stored water a useful height advantage.', 'The sea must rise high enough to cover the mill wheel.', 'The miller must release all stored water before the wheel starts.'], 'The outside sea must fall enough to give the stored water a useful height advantage.', 'The pond has already filled, but the passage says the sea outside must fall enough to create a useful height difference. Another incoming tide is unnecessary at this stage; the wheel is driven by released pond water rather than being covered by the sea; and the wheel starts as water is released, not after all of it has gone.', 1, 'normal'),
  ('e285562a-5ee4-4af5-951a-43579930a57e', '2ec286c7-0754-4e7c-b994-202d18e04bc1', 'What does the Totton and Eling example mainly illustrate?', ARRAY['That tide mills had no machinery in common with river mills', 'That the dam served only as a bridge across the inlet', 'That tidal water management and familiar milling machinery operated together', 'That every tide mill used exactly the same set of millstones'], 'That tidal water management and familiar milling machinery operated together', 'The example combines a dam and sluice gear with a wheel and millstones. The passage explicitly notes shared machinery, gives the dam a water-management role and does not generalise exact equipment to every mill.', 2, 'normal'),
  ('c66ec54c-2c9b-432b-889c-0a82115d993c', '2ec286c7-0754-4e7c-b994-202d18e04bc1', 'Suppose the sluice remains closed while the sea falls. Which outcome follows most directly from the account?', ARRAY['The difference in water levels can grow before the miller releases pond water.', 'The wheel must turn at a constant speed as the tide falls.', 'The pond immediately empties into the estuary.', 'The next incoming tide can no longer refill the pond.'], 'The difference in water levels can grow before the miller releases pond water.', 'Closed gates retain pond water while the sea falls, so the height difference may increase. No constant wheel speed, immediate emptying or permanent block to refilling follows.', 3, 'hard')
;

-- Passage 4: Fire in the Walls of Scottish Hillforts
INSERT INTO verbal_reasoning_passages (id, title, body, is_free) VALUES
  ('cd520cf5-93e8-452f-847f-d0775a298a56', 'Fire in the Walls of Scottish Hillforts', 'At some Scottish hillforts, parts of ancient stone ramparts have been vitrified: intense heat has fused some of the rock into a glassy mass. The effect is a trace of burning, but it does not by itself reveal who lit a fire or why. One proposed explanation was that builders deliberately fired the walls to strengthen them. Archaeologists now generally reject vitrification as an intended construction technique. Burned timber within a stone rampart can supply enough heat to fuse some surrounding rock, but the circumstances of a particular fire may remain uncertain.

The White Caterthun in Angus has a great stone fort with evidence of vitrification. Its neighbouring Brown Caterthun has a more complicated sequence. Excavation found parts of its earthworks had been maintained, burned and rebuilt over time. Historic Environment Scotland notes that both places had various earthworks and that their exact functions remain debated. They may have served defensive and ceremonial roles. The visible evidence supports a history more complicated than a single episode of construction followed by abandonment.

Another Scottish example, the dun at Rahoy, offers a closer view of a burned wall. A dun is a small fortified settlement. Excavators found cavities where timber beams had once passed through sections of vitrified material. This helps explain a physical route from timber-laced stonework to fused rock when the timber burned. It does not identify the person who set the fire. At Rahoy, only part of the interior was fully excavated, so any account of activity across the entire site must be cautious. Read together, the sites show how a material trace can reveal a process while leaving the human intention behind it open to further evidence.', false)
;

INSERT INTO verbal_reasoning_questions
  (id, passage_id, question_text, options, correct_answer, answer_reason, order_index, difficulty)
VALUES
  ('ab07c151-b7ee-49ce-a25c-2cdf490608ad', 'cd520cf5-93e8-452f-847f-d0775a298a56', 'The White Caterthun has stonework showing evidence of vitrification.', ARRAY['True', 'False', 'Can''t tell'], 'True', 'The passage explicitly says the White Caterthun has a stone fort with evidence of vitrification.', 0, 'normal'),
  ('71f4bc3c-581c-4e67-87ae-bad66f99de62', 'cd520cf5-93e8-452f-847f-d0775a298a56', 'The Brown Caterthun was built and then abandoned without any later rebuilding.', ARRAY['True', 'False', 'Can''t tell'], 'False', 'The Brown Caterthun had earthworks that were burned and rebuilt over time, contradicting the single-build claim.', 1, 'normal'),
  ('2fb8771b-ad3d-413b-af0c-fa6b585ed564', 'cd520cf5-93e8-452f-847f-d0775a298a56', 'At Rahoy, the fire in the rampart was started by attackers.', ARRAY['True', 'False', 'Can''t tell'], 'Can''t tell', 'The text says timber burned but does not identify who lit the fire. Attackers are neither confirmed nor ruled out.', 2, 'normal'),
  ('618fbfcf-eb85-4baf-a831-1a1c5d13ee57', 'cd520cf5-93e8-452f-847f-d0775a298a56', 'The cavities at Rahoy establish why its wall was burned.', ARRAY['True', 'False', 'Can''t tell'], 'False', 'The cavities show that timber once passed through the wall and help explain how burning fused the rock. The passage says this physical trace does not establish who lit the fire or the human intention behind it, so the claim that it establishes why is contradicted.', 3, 'hard')
;

-- Passage 5: Catching Water from Coastal Fog
INSERT INTO verbal_reasoning_passages (id, title, body, is_free) VALUES
  ('2ce4672d-1921-4669-bfe8-8228e7d280d1', 'Catching Water from Coastal Fog', 'Where wind carries fog inland, suspended mesh panels can collect some of its tiny water droplets. Droplets strike the strands, combine into larger drops and slide towards a gutter and storage vessel below. A solid panel might seem better because it has no holes, but it diverts much of the airflow around itself. An open mesh lets more fog pass through its collecting area. Fog collection therefore depends on both interception of droplets and their removal from the strands before wind carries them away.

Researchers at MIT, working with colleagues in Chile, examined three features of a mesh: the thickness of its strands, the gaps between them and the coating on their surfaces. They found that commonly used plastic meshes had strands and gaps too large for efficient collection under mild fog conditions. A finer experimental mesh was predicted to capture a larger share of the water in air passing through it. Its coating helped droplets slide down promptly into a gutter rather than remain on the strands. These findings describe an improvement under particular conditions, not a guarantee of a fixed daily water supply everywhere.

The research took place in a context where coastal fog can reach very dry land near Chile''s Atacama Desert. The team installed test screens on hilltops north of Santiago to study water yield and durability over time. Wind strength and fog density still matter: a mesh cannot collect droplets that never reach it. The researchers also discussed placing several meshes one behind another to intercept water left in the airflow. Yet extra screens would have to be assessed as a system; the passage gives no measured annual yield for such a series. The attraction of the approach is its simple physical mechanism, while its practical output depends on local conditions and the design used.', false)
;

INSERT INTO verbal_reasoning_questions
  (id, passage_id, question_text, options, correct_answer, answer_reason, order_index, difficulty)
VALUES
  ('d26f137c-d687-41e6-8cef-be04c3b5c366', '2ce4672d-1921-4669-bfe8-8228e7d280d1', 'A solid panel diverts less airflow than an open mesh because it has no holes.', ARRAY['True', 'False', 'Can''t tell'], 'False', 'The passage explicitly says a solid panel diverts much of the airflow around itself, while an open mesh lets more fog pass through its collecting area. Having no holes does not produce the claimed reduction in diverted airflow.', 0, 'normal'),
  ('d66695e8-722b-485d-8bbb-adcd35f4eb7a', '2ce4672d-1921-4669-bfe8-8228e7d280d1', 'The researchers examined mesh gaps as well as strand thickness and surface coating.', ARRAY['True', 'False', 'Can''t tell'], 'True', 'The passage explicitly lists strand thickness, the size of the gaps between strands, and the coating on the strands as the three features examined. Since the statement names two of these features and includes the coating, it is confirmed rather than contradicted or left unknown.', 1, 'normal'),
  ('913ef3de-1793-473a-97d1-59cc056be21a', '2ce4672d-1921-4669-bfe8-8228e7d280d1', 'At the Chilean test site, three experimental meshes in series would double the annual water yield of one mesh.', ARRAY['True', 'False', 'Can''t tell'], 'Can''t tell', 'Several meshes in series are discussed as a possible way to intercept water left in the airflow. The passage provides no measured annual yield or three-versus-one comparison at the Chilean site, so doubling is neither established nor contradicted.', 2, 'hard'),
  ('717397ca-99be-4ced-9ad8-4d3f1fbfbd83', '2ce4672d-1921-4669-bfe8-8228e7d280d1', 'The passage says that even an improved mesh needs fog droplets to reach it.', ARRAY['True', 'False', 'Can''t tell'], 'True', 'It explicitly states that a mesh cannot collect droplets that never reach it, so improved design does not remove the dependence on local fog and wind.', 3, 'normal')
;
